# https://travis-ci.org/spyder-ide/spyder

language: python
sudo: false

env:
  global:
    - MINICONDA_VERSION="latest"
    - MINICONDA_LINUX="Linux-x86_64"
    - MINICONDA_OSX="MacOSX-x86_64"

matrix:
  include:
    # Linux using pip packages
    - python: "2.7"
      env: USE_QT_API=PyQt4 USE_CONDA=false
      os: linux
    - python: "3.4"
      env: USE_QT_API=PyQt4 USE_CONDA=false
      os: linux
    # Linux using conda packages
    - python: "2.7"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "2.7"
      env: USE_QT_API=PyQt5 USE_CONDA=true
      os: linux
    - python: "3.4"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "3.5"
      env: USE_QT_API=PyQt4 USE_CONDA=true
      os: linux
    - python: "3.5"
      env: USE_QT_API=PyQt5 USE_CONDA=true
      os: linux

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export FULL_SPYDER_CLONE=$HOME/spy-clone"

install:
  - ./continuous_integration/travis/install.sh;
  - if [ "$USE_CONDA" = true ]; then source activate test-environment; fi
  - export PATH="$HOME/miniconda/bin:$PATH";

script:
  - ./continuous_integration/travis/build_test.sh
  - ./continuous_integration/travis/run_test.sh
  - ./continuous_integration/travis/modules_test.sh
