# https://travis-ci.org/spyder-ide/spyder

language: generic
dist: xenial
services:
    - xvfb

matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION=2.7 USE_CONDA=yes RUN_SLOW=true
    - env: PYTHON_VERSION=2.7 USE_CONDA=yes RUN_SLOW=false
    - env: PYTHON_VERSION=3.7 USE_CONDA=no RUN_SLOW=true
    - env: PYTHON_VERSION=3.7 USE_CONDA=no RUN_SLOW=false

before_install:
  # Avoid inotify errors when running projects test with Kite installed
  - sudo sysctl -n -w fs.inotify.max_user_watches=16384
  # Avoid annoying focus problems when running tests
  # See discussion in e.g. https://github.com/spyder-ide/spyder/pull/6132
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager xterm libxkbcommon-x11-0
  - matchbox-window-manager&
  - sleep 5

install:
  - ./continuous_integration/travis/install.sh

script:
  - ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh

after_success:
  - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate test && coveralls
