# https://travis-ci.org/spyder-ide/spyder

language: python
dist: trusty
sudo: false

matrix:
  include:
    # This never ends!
    #- python: "2.7"
    #  env: TEST_MODULES=false
    #  os: linux
    - python: "2.7"
      env: TEST_MODULES=true
      os: linux
    - python: "3.5"
      env: TEST_MODULES=false
      os: linux
    - python: "3.5"
      env: TEST_MODULES=true
      os: linux
    - python: "3.4"
      env: TEST_MODULES=false
      os: linux

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - ./continuous_integration/circle/install.sh;

script:
  - |
    if [ "$TEST_MODULES" = "true" ]; then
        ./continuous_integration/travis/modules_test.sh
    else
        ./continuous_integration/circle/test-qt4.sh
    fi
