name: spy-inst
channels:
  - napari/label/bundle_tools_3
  - conda-forge
dependencies:
  - boa
  - conda-standalone
  - constructor
  - gitpython
  - menuinst
  - ruamel.yaml.jinja2
  - setuptools_scm
