version: 2

main: &main
    machine: true
    steps:
      - checkout
      - run:
          command: docker pull dorowu/ubuntu-desktop-lxde-vnc:xenial
      - run:
          name: Install system packages
          command: |
            sudo apt-get -qq update
            sudo apt-get install libegl1-mesa
      - run:
          command: ./continuous_integration/travis/install.sh
      - run:
          command: ./continuous_integration/circle/modules_test.sh || ./continuous_integration/circle/modules_test.sh

jobs:
  python2.7:
    <<: *main
    environment:
      - PYTHON_VERSION: "2.7"
      - USE_CONDA: "yes"

  python3.5:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.5"
      - USE_CONDA: "no"

  python3.6:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.6"
      - USE_CONDA: "yes"

  python3.7:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.7"
      - USE_CONDA: "yes"

workflows:
  version: 2
  build_and_test:
    jobs:
      - python2.7
      - python3.5
      - python3.6
      - python3.7
