name: Macos tests

on:
  push:
    branches:
    - master
    - 2.x
  pull_request:
    branches:
    - master
    - 2.x

jobs:
  macos:
    name: Mac Py${{ matrix.PYTHON_VERSION }}
    runs-on: macos-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'macos'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['2.7', '3.6', '3.7', '3.8']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: test
           auto-update-conda: true
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install package dependencies
        shell: bash -l {0}
        run: conda install --file requirements/posix.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install nomkl -y -q
          conda install --file requirements/tests.txt -y -q
          if [ "$PYTHON_VERSION" != "2.7" ]; then conda install -y -q jedi=0.17.2; fi
      - name: Install Package
        shell: bash -l {0}
        run: pip install -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: pytest spyder_kernels --cov=spyder_kernels -x -vv
