name: Mac tests

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Mac Py${{ matrix.PYTHON_VERSION }}
    runs-on: macos-latest
    env:
      CI: 'true'
      OS: 'macos'
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.8', '3.7', '3.6', '2.7']
    timeout-minutes: 10
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: ${{ runner.os }}-${{ matrix.PYTHON_VERSION }}-pip-
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: 'x64'
      - name: Create Jedi environment for testing
        if: matrix.PYTHON_VERSION != '2.7'
        run: |
          python3 -m venv /tmp/pyenv
          /tmp/pyenv/bin/python -m pip install loghub
      - run: python -m pip install --upgrade pip setuptools
      - run: pip install -e .[all,test]
      - run: py.test -v test/
