channels:
- conda-forge
dependencies:
# We can not refer to an environment.yml file from another
# So to get performant launches on mybinder.org, we have copied
# the contents of requirements/main.yml and requirements/linux.yml
# to this file.
# Please *DO NOT* make changes directly just to here - make changes
# to requirements/main.yml, and copy it here.
- atomicwrites >=1.2.0
- chardet >=2.0.0
- cloudpickle >=0.5.0
- cookiecutter >=1.6.0
- diff-match-patch >=20181111
- intervaltree >=3.0.2
- ipython >=8.13.0,<9.0.0,!=8.17.1
- jedi >=0.17.2,<0.20.0
- jellyfish >=0.7
- jsonschema >=3.2.0
- keyring >=17.0.0
- nbconvert >=4.0
- numpydoc >=0.6.0
- parso >=0.7.0,<0.9.0
- pexpect >=4.4.0
- pickleshare >=0.4
- psutil >=5.3
- pygments >=2.0
- pylint >=2.5.0,<3.1
- pylint-venv >=3.0.2
- pyls-spyder >=0.4.0
- pyqt >=5.10,<5.16
- pyqtwebengine >=5.10,<5.16
- python-lsp-black >=2.0.0,<3.0.0
- python-lsp-server >=1.10.0,<1.11.0
- pyxdg >=0.26
- pyzmq >=22.1.0
- qdarkstyle >=3.2.0,<3.3.0
- qstylizer >=0.2.2
- qtawesome >=1.2.1
- qtconsole >=5.5.1,<5.6.0
- qtpy >=2.1.0
- rtree >=0.9.7
- setuptools >=49.6.0
- sphinx >=0.6.6
- spyder-kernels >=2.5.0,<2.6.0
- textdistance >=4.2.0
- three-merge >=0.1.1
- watchdog >=0.10.3

# We can not refer to an environment.yml file from another
# So to get performant launches on mybinder.org, we have copied
# the contents of this requirements/tests.yml to this file.yml.
# Please *DO NOT* make changes directly just to here - make changes
# to requirements/tests.yml, and copy it here.
- coverage
- cython
- flaky
- matplotlib
- pandas
- pillow
- pytest <7.0
- pytest-cov
- pytest-lazy-fixture
- pytest-mock
- pytest-order
- pytest-qt
- pytest-timeout
- pyyaml
- scipy
- sympy

# Required for desktop view on mybinder.org
- websockify
- pip:
  - jupyter-desktop-server
