channels:
- conda-forge/label/spyder_kernels_dev
- conda-forge/label/spyder_kernels_rc
- conda-forge
dependencies:
# We can not refer to an environment.yml file from another
# So to get performant launches on mybinder.org, we have copied
# the contents of requirements/main.yml and requirements/linux.yml
# to this file.
# Please *DO NOT* make changes directly just to here - make changes
# to requirements/main.yml, and copy it here.
- aiohttp >=3.11.2
- asyncssh >=2.14.0,<3.0.0
- atomicwrites >=1.2.0
- bcrypt >=4.3.0
- chardet >=2.0.0
- cloudpickle >=0.5.0
- cookiecutter >=1.6.0
- diff-match-patch >=20181111
- fcitx-qt5 >=1.2.7
- fzf >=0.42.0
- importlib-metadata >=4.6.0
- intervaltree >=3.0.2
- ipython >=8.15.0,<10.0.0,!=8.17.1,!=9.1.0,!=9.2.0,!=9.3.0,!=9.4.0
- ipython_pygments_lexers >=1.0
- jedi >=0.17.2,<0.20.0
- lxml >=4.9.0
- jellyfish >=0.7
- jsonschema >=3.2.0
- keyring >=17.0.0
- nbconvert >=4.0
- numpydoc >=0.6.0
- packaging >=20.0
- parso >=0.7.0,<0.9.0
- pexpect >=4.4.0
- pickleshare >=0.4
- psutil >=5.3
- pygithub >=2.3.0
- pygments >=2.0
- pylint >=3.1,<4
- pylint-venv >=3.0.2
- pyls-spyder >=0.4.0
- pyqt >=5.15,<5.16
- pyqtwebengine >=5.15,<5.16
- python-lsp-black >=2.0.0,<3.0.0
- python-lsp-ruff >=2.3.0,<3.0.0
- python-lsp-server >=1.13.0,<1.14.0
- pyuca >=1.2
- pyxdg >=0.26
- pyzmq >=24.0.0
- qdarkstyle >=3.2.0,<3.3.0
- qstylizer >=0.2.2
- qtawesome >=1.4.0,<1.5.0
- qtconsole >=5.7.0,<5.8.0
- qtpy >=2.4.0
- rtree >=0.9.7
- sphinx >=7.2.0
- spyder-kernels >=3.1.0b1,<3.2.0a2
- superqt >=0.6.2,<1.0.0
- textdistance >=4.2.0
- three-merge >=0.1.1
- watchdog >=0.10.3
- yarl >=1.9.4

# We can not refer to an environment.yml file from another
# So to get performant launches on mybinder.org, we have copied
# the contents of this requirements/tests.yml to this file.yml.
# Please *DO NOT* make changes directly just to here - make changes
# to requirements/tests.yml, and copy it here.
- coverage
- cython
- flaky
- matplotlib
- pandas
- pillow
- pytest <8.0
- pytest-cov
- pytest-lazy-fixture
- pytest-mock
- pytest-order
- pytest-qt
- pytest-timeout
- pyyaml
- scipy
- sympy

# Required for desktop view on mybinder.org
- websockify
- pip:
  - jupyter-remote-desktop-proxy
