channels:
- manics # Used by jupyter-desktop-server
dependencies:
# We can not refer to an environment.yml file from another
# So to get performant launches on mybinder.org, we have copied
# the contents of this requirements/conda.txt to this file.yml.
# Please *DO NOT* make changes directly just to here - make changes
# to requirements/conda.txt, and copy it here.
- applaunchservices >=0.1.7
- atomicwrites >=1.2.0
- chardet >=2.0.0
- cloudpickle >=0.5.0
- diff-match-patch >=20181111
- intervaltree
- ipython >=4.0
- jedi =0.17.1
- keyring
- nbconvert >=4.0
- numpydoc >=0.6.0
- paramiko >=2.4.0
- parso =0.7.0
- pexpect >=4.4.0
- pickleshare >=0.4
- psutil >=5.3
- pygments >=2.0
- pylint >=1.0
- pyqt <5.13
- pyyaml
# NOTE: There's no need to set constraints for python-language-server
# here because Spyder uses the subrepo for it when started in Binder.
- python-language-server
- pyxdg >=0.26
- pyzmq >=17
- qdarkstyle >=2.8
- qtawesome >=0.5.7
- qtconsole >=4.6.0
- qtpy >=1.5.0
- rtree >=0.8.3
- sphinx >=0.6.6
# NOTE: There's no need to set constraints for spyder-kernels here
# because Spyder uses the subrepo for it when started in Binder.
- spyder-kernels
- watchdog

# We can not refer to an environment.yml file from another
# So to get performant launches on mybinder.org, we have copied
# the contents of this requirements/tests.txt to this file.yml.
# Please *DO NOT* make changes directly just to here - make changes
# to requirements/tests.txt, and copy it here.
- coverage <5.0
- cython
- flaky
- matplotlib
- mock
- pandas
- pillow
- pytest <5.0
- pytest-mock
- pytest-cov
- pytest-qt
- pytest-ordering
- pytest-lazy-fixture
- pytest-faulthandler <2.0
- pytest-xvfb
- scipy
- sympy

# Required for jupyter-desktop-server
- websockify
- pip:
    - jupyter-desktop-server
