name: Purge caches
on:
  schedule:
    # 17:20 UTC Friday
    - cron: "20 17 * * 5"

  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Purge Cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Test purge cache."

  run-test-files:
    name: Run test-files
    needs:
      - cleanup
    uses: ./.github/workflows/test-files.yml

  run-test-linux:
    name: Run test-linux
    needs:
      - cleanup
    uses: ./.github/workflows/test-linux.yml

  run-test-mac:
    name: Run test-mac
    needs:
      - cleanup
    uses: ./.github/workflows/test-mac.yml

  run-test-remoteclient:
    name: Run test-remoteclient
    needs:
      - cleanup
    uses: ./.github/workflows/test-remoteclient.yml

  run-test-win:
    name: Run test-win
    needs:
      - cleanup
    uses: ./.github/workflows/test-win.yml
